name: fetch-etf
on:
  schedule:
    - cron: '15 23 * * *'        # 每天 UTC 23:15
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write            # 允许推送
    steps:
      - uses: actions/checkout@v4

      - name: grab farside
        run: |
          curl -s https://farside.co.uk/btc/ -o page.html
          FLOW=$(grep -Eo '<tr><td[^>]*>[0-9]{2} [A-Z][a-z]{2} 20[0-9]{2}.*' page.html \
                 | head -1 \
                 | sed -E 's/.*<td[^>]*>([0-9\.\-(),]+)<\/td><\/tr>.*/\1/' \
                 | tr -d '(),')
          [[ -z "$FLOW" ]] && FLOW=0
          echo "{\"flow\":${FLOW}}" > netflow.json
          cat netflow.json

      - name: push to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: main      # 关键：推回 main 分支
