name: fetch-etf
on:
  schedule:
    - cron: '15 23 * * *'        # 每天 UTC 23:15
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:               # 允许工作流写入仓库
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: grab farside
        run: |
          curl -s https://farside.co.uk/btc/ -o page.html
          FLOW=$(grep -Eo 'Net Inflow[^$]+\$[0-9,]+' page.html \
                 | head -1 | grep -Eo '[0-9,]+' | tr -d ',')
          [[ -z "$FLOW" ]] && FLOW=0
          echo "{\"flow\":${FLOW}}" > netflow.json

      - name: push to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: main          # ← **关键新增行**
