name: fetch-etf

on:
  schedule:
    # 每天 UTC 23:15（北京时间 07:15）自动跑一次
    - cron: '15 23 * * *'
  workflow_dispatch:      # 允许你点按钮手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash        # 指定统一用 bash，避免 /bin/sh 的差异

    steps:
      # 1. 拉下当前仓库
      - uses: actions/checkout@v4

      # 2. 抓取 Farside 页面并提取“Total”列最后一个数字
      - name: grab farside
        run: |
          set -e

          # 下载页面
          curl -fsSL https://farside.co.uk/btc/ -o page.html

          # 当天日期，如 “07 May 2025”
          TODAY=$(date +"%d %b %Y")

          # awk 以 </tr> 为记录分隔符；匹配当天行后打印并退出
          LINE=$(awk -v RS='</tr>' -v today="$TODAY" '$0 ~ today {print; exit}' page.html)

          # 从这行里抓所有 “>数字<” 或 “>-数字<”，取最后一个
          FLOW=$(grep -oE '>-?[0-9]+([.][0-9]+)?<' <<<"$LINE" | tail -1 | tr -d '<>')

          # 若为空则置 0
          [[ -z "$FLOW" ]] && FLOW=0

          echo "{\"flow\":${FLOW}}" > netflow.json
          echo "Fetched flow = ${FLOW}"

      # 3. 推送结果回 main，让 GitHub Pages 重新部署
      - name: push to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: main
